[package]
name = "day4"
version = "0.1.0"
authors = ["mattlennon3 <mattlennon3@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.2"
